import { useEffect, useState } from "react";
import { Link, NavLink, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, ArrowUpRight, Heart, HeartHandshake, Home, LogOut, MapPin, Search, ShieldCheck, UserRound, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import SEO from "@/components/SEO";
import { volunteerDepartments, volunteerFields } from "@/lib/volunteerFields";
import { PORTAL_TOKEN_KEY, portalRequest, socialLabels, type PortalMe, type PortalMember } from "@/lib/volunteerPortal";
import VolunteerProfileEditor from "./VolunteerProfileEditor";
import "./portal.css";

const departmentName = (code: string) => volunteerDepartments.find(d=>d.code===code)?.label || code || "OPHEG volunteer";
function Avatar({ name, url, large = false }: {name:string;url?:string|null;large?:boolean}) { return <span className={`vp-avatar ${large ? "large" : ""}`}>{url ? <img src={url} alt=""/> : name.slice(0,1).toUpperCase()}</span>; }
function QueryProblem({ retry }: {retry:()=>void}) { return <div className="vp-panel vp-empty" role="alert"><h2>We couldn’t load this just yet.</h2><p>Please try again. If this is a profile, it may no longer be shared.</p><Button onClick={retry} variant="outline">Try again</Button></div>; }
function MemberCard({ member }: {member:PortalMember}) { return <Link to={`/volunteers/members/${member.id}`} className={`vp-member-card tone-${member.id%3}`}><div className="vp-member-banner" aria-hidden="true"><span/><i/></div><div className="vp-member-body"><Avatar name={member.name} url={member.photoUrl}/><span className="vp-member-arrow"><ArrowUpRight size={18}/></span><span className="vp-department">{departmentName(member.department)}</span><h3>{member.preferredName || member.name}</h3><p className="vp-handle">@{member.handle}</p><p className="vp-member-bio">{member.bio || member.role || "Making a difference with OPHEG."}</p><div className="vp-member-location"><MapPin size={13}/>{[member.city,member.country].filter(Boolean).join(", ") || "OPHEG community"}</div></div></Link>; }
function PortalHome({ me }: {me:PortalMe}) {
  const community = useQuery({queryKey:["volunteer-portal","community-home"],queryFn:({signal})=>portalRequest<{members:PortalMember[];total:number}>("directory",{signal}),retry:1,staleTime:60000});
  const essentials = volunteerFields.filter(field=>field.required);
  const filled = essentials.filter(field=>String(me.details[field.key] || "").trim()).length;
  const percent = Math.round(filled/essentials.length*100);
  return <><div className="vp-welcome vp-pattern"><div><span className="vp-eyebrow"><span className="vp-online-dot"/> YOUR PEOPLE. YOUR PURPOSE.</span><h1>Hello, {String(me.details.preferredName || me.details.name || "volunteer").split(" ")[0]}.<br /><em>You belong here.</em></h1><p>Big change begins with people like you.<br />Let’s keep making a difference, together.</p><Link to="/volunteers/community" className="vp-white-button">Meet your community <ArrowUpRight size={17}/></Link></div><div className="vp-welcome-art" aria-hidden="true"><HeartHandshake size={82}/><span>HEALTHIER<br /><strong>TOGETHER.</strong></span></div></div>
    <div className="vp-overview"><section className="vp-panel vp-progress-card"><div className="vp-section-icon"><UserRound size={20}/></div><div><p className="vp-eyebrow">YOUR PROFILE</p><h2>{percent}% of essential details complete</h2><div className="vp-progress-track" role="progressbar" aria-valuenow={percent} aria-valuemin={0} aria-valuemax={100} aria-label="Profile completion"><span style={{width:`${percent}%`}}/></div><p>A current profile helps us connect you to the right opportunities.</p></div><Link to="/volunteers/profile" aria-label="Edit your profile"><ArrowUpRight size={22}/></Link></section><section className="vp-panel vp-community-status"><span className="vp-section-icon green"><ShieldCheck size={20}/></span><h2>{me.profile.visible ? "You’re in the community." : "Your profile, your choice."}</h2><p>{me.profile.visible ? `Find yourself at @${me.profile.handle}. You decide which links and photo to share.` : "Introduce yourself to other volunteers by joining the member directory."}</p><Link to="/volunteers/profile">Manage visibility <ArrowRight size={14}/></Link></section></div>
    <div className="vp-section-top"><div><p className="vp-eyebrow">MANY TALENTS. ONE MISSION.</p><h2>People making a difference</h2></div><Link to="/volunteers/community">View community <ArrowRight size={15}/></Link></div>
    {community.isPending ? <p role="status">Loading your community…</p> : community.isError ? <QueryProblem retry={()=>void community.refetch()}/> : community.data.members.length ? <div className="vp-members-grid">{community.data.members.slice(0,3).map(member=><MemberCard key={member.id} member={member}/>)}</div> : <div className="vp-panel vp-empty"><Users size={35}/><h2>Your community starts with you.</h2><p>No profiles have been shared yet. Add your introduction and choose to appear in the directory.</p><Link to="/volunteers/profile">Introduce yourself <ArrowRight size={14}/></Link></div>}
    <div className="vp-mission-note"><Heart size={18}/><p>Every conversation, every connection, every act of care brings our mission a little closer.</p><span>THAT’S THE OPHEG WAY.</span></div>
  </>;
}
function Community() {
  const [search,setSearch]=useState(""); const [query,setQuery]=useState(""); const [page,setPage]=useState(0);
  useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);setPage(0);},300);return()=>clearTimeout(timer);},[search]);
  const directory=useQuery({queryKey:["volunteer-portal","directory",query,page],queryFn:({signal})=>portalRequest<{members:PortalMember[];total:number;pageSize:number}>(`directory?search=${encodeURIComponent(query)}&page=${page}`,{signal}),retry:1,refetchInterval:240000});
  return <><div className="vp-page-title"><div><p className="vp-eyebrow">BETTER TOGETHER</p><h1>Meet your community.</h1><p>Find shared interests. Exchange ideas. Make a new connection.</p></div><span className="vp-heading-flower" aria-hidden="true"><Users size={29}/></span></div><div className="vp-directory-tools"><label><Search size={18}/><span className="sr-only">Search volunteers</span><Input value={search} onChange={e=>setSearch(e.target.value)} maxLength={120} placeholder="Search name, handle, skills, or location…"/></label><span>{directory.data ? `${directory.data.total} shared profiles` : "Volunteer directory"}</span></div>
    {directory.isPending ? <p role="status">Finding your people…</p> : directory.isError ? <QueryProblem retry={()=>void directory.refetch()}/> : directory.data.members.length ? <div className="vp-members-grid">{directory.data.members.map(member=><MemberCard key={member.id} member={member}/>)}</div> : <div className="vp-panel vp-empty"><Search size={32}/><h2>{query ? "No matches this time." : "Room for new connections."}</h2><p>{query ? "Try a different name, skill, or location." : "Volunteers will appear here when they choose to share their profile."}</p></div>}
    <div className="vp-pagination"><Button variant="outline" disabled={page===0||directory.isFetching} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page+1}</span><Button variant="outline" disabled={!directory.data||directory.data.members.length<24||(page+1)*24>=directory.data.total||directory.isFetching} onClick={()=>setPage(page+1)}>Next</Button></div><p className="vp-directory-note"><ShieldCheck size={14}/> Only signed-in volunteers can view these shared profiles.</p>
  </>;
}
function MemberDetails() {
  const {id}=useParams();
  const member=useQuery({queryKey:["volunteer-portal","member",id],queryFn:({signal})=>portalRequest<PortalMember>(`members/${id}`,{signal}),retry:1,refetchInterval:240000});
  if(member.isPending)return <p role="status">Loading profile…</p>;
  if(member.isError)return <QueryProblem retry={()=>void member.refetch()}/>;
  const data=member.data;
  return <><Link to="/volunteers/community" className="vp-back-link">← Back to community</Link><article className="vp-member-detail"><div className="vp-detail-banner vp-pattern"><span>CONNECTED BY PURPOSE.</span></div><div className="vp-detail-intro"><Avatar name={data.name} url={data.photoUrl} large/><span className="vp-department">{departmentName(data.department)}</span><h1>{data.name}</h1><p className="vp-handle">@{data.handle}</p><p><MapPin size={15}/>{[data.city,data.country].filter(Boolean).join(", ")}</p></div><div className="vp-detail-grid"><section><p className="vp-eyebrow">THE PERSON BEHIND THE PURPOSE</p><h2>A little about me</h2><p className="vp-prewrap">{data.bio || "This volunteer hasn’t added an introduction yet."}</p>{[["My role",data.role],["Skills & strengths",data.skills],["Languages",data.languages],["Programs I support",data.programs]].filter(([,value])=>value).map(([label,value])=><div className="vp-detail-block" key={label}><h3>{label}</h3><p className="vp-prewrap">{value}</p></div>)}</section><aside><div className="vp-connect-card"><HeartHandshake size={27}/><h2>Start a connection.</h2><p>Find me on these platforms.</p>{Object.entries(socialLabels).filter(([key])=>data[key as keyof typeof socialLabels]).map(([key,label])=><a key={key} href={data[key as keyof typeof socialLabels]} target="_blank" rel="noopener noreferrer">{label}<ArrowUpRight size={16}/></a>)}{!Object.keys(socialLabels).some(key=>data[key as keyof typeof socialLabels])&&<p>No social links shared yet.</p>}</div></aside></div></article></>;
}
export default function VolunteerPortal() {
  const navigate=useNavigate(); const cache=useQueryClient(); const [session,setSession]=useState(()=>Boolean(sessionStorage.getItem(PORTAL_TOKEN_KEY))); const [logoutError,setLogoutError]=useState(""); const [leaving,setLeaving]=useState(false);
  useEffect(()=>{const expire=()=>{setSession(false);cache.removeQueries({queryKey:["volunteer-portal"]});};window.addEventListener("volunteer-session-expired",expire);return()=>window.removeEventListener("volunteer-session-expired",expire);},[cache]);
  const me=useQuery({queryKey:["volunteer-portal","me"],queryFn:({signal})=>portalRequest<PortalMe>("me",{signal}),enabled:session,retry:1,staleTime:60000});
  async function signout(){setLeaving(true);setLogoutError("");try{await portalRequest("logout",{method:"POST"});sessionStorage.removeItem(PORTAL_TOKEN_KEY);cache.removeQueries({queryKey:["volunteer-portal"]});navigate("/volunteers/login",{replace:true});}catch{setLogoutError("Could not sign out. Please try again.");}finally{setLeaving(false);}}
  if(!session)return <Navigate to="/volunteers/login" replace/>;
  const update=(value:PortalMe)=>{cache.setQueryData(["volunteer-portal","me"],value);void cache.invalidateQueries({queryKey:["volunteer-portal","directory"]});void cache.invalidateQueries({queryKey:["volunteer-portal","community-home"]});void cache.invalidateQueries({queryKey:["volunteer-portal","member"]});};
  return <div className="vp vp-app"><SEO title="Volunteer community | OPHEG" description="Connect with the OPHEG volunteer community" noindex/><a className="vp-skip" href="#volunteer-main">Skip to content</a><aside className="vp-sidebar"><Link to="/volunteers" className="vp-brand"><img src="/logo-full.png" alt="OPHEG"/><span>THE VOLUNTEER COMMUNITY</span></Link><p className="vp-nav-label">YOUR SPACE</p><nav aria-label="Volunteer navigation">{[{path:"/volunteers",label:"My home",icon:Home,end:true},{path:"/volunteers/community",label:"Community",icon:Users},{path:"/volunteers/profile",label:"My profile",icon:UserRound}].map(item=><NavLink key={item.path} to={item.path} end={item.end} className={({isActive})=>isActive ? "is-active" : ""}><item.icon size={18}/>{item.label}<ArrowUpRight size={14}/></NavLink>)}</nav><div className="vp-sidebar-bottom"><div className="vp-sidebar-mission"><Heart size={25}/><h3>Small actions.<br />Lasting impact.</h3><p>Thank you for showing up for a healthier world.</p><span aria-hidden="true"/></div><Link to="/" className="vp-visit">Visit OPHEG website <ArrowUpRight size={14}/></Link><button type="button" onClick={()=>void signout()} disabled={leaving}><LogOut size={16}/>{leaving ? "Signing out…" : "Sign out"}</button>{logoutError&&<p role="alert" className="vp-error">{logoutError}</p>}</div></aside><div className="vp-workspace"><header className="vp-topbar"><span><span className="vp-online-dot"/> A community with purpose.</span>{me.data&&<Link to="/volunteers/profile"><span>{String(me.data.details.preferredName||me.data.details.name)}</span><Avatar name={String(me.data.details.name)} url={me.data.photoUrl}/></Link>}</header><main id="volunteer-main" className="vp-main" tabIndex={-1}>{me.isPending ? <div className="vp-panel vp-empty" role="status">Opening your volunteer space…</div> : me.isError ? <QueryProblem retry={()=>void me.refetch()}/> : <Routes><Route index element={<PortalHome me={me.data}/>}/><Route path="community" element={<Community/>}/><Route path="profile" element={<VolunteerProfileEditor me={me.data} onSaved={update}/>}/><Route path="members/:id" element={<MemberDetails/>}/><Route path="*" element={<Navigate to="/volunteers" replace/>}/></Routes>}<footer className="vp-footer"><span>© {new Date().getFullYear()} OPHEG</span><span>Taking health to the communities. <Heart size={12}/></span></footer></main></div></div>;
}
